FROM node:12.4.0-alpine as build

WORKDIR /app


COPY package.json package-lock.json ./
RUN npm install

# Copy the main application
COPY . ./

# Arguments
ARG API_BASE_URL
ENV API_BASE_URL=${API_BASE_URL}

# Build the application
RUN npm install
RUN npm run ng build -- --deploy-url=/ --prod

#### Stage 2: Serve the React application from Nginx
FROM nginx:1.17.0-alpine


# Copy the angular build from Stage 1
COPY --from=build /app/target/classes/static /usr/share/nginx/html

# Copy our custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to the Docker host, so we can access it
# from the outside.
EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
