version: '3.7'

services:
  app-server:
    build:
      context: .
      dockerfile: ./devops/Dockerfile-spring
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/master?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: .
      dockerfile: ./devops/Dockerfile-angular
      args:
        API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: master
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
